package manifest

// table is the authoritative classification of every _OPS op (EDITOR_PLUGIN_PLAN.md
// §5.3), produced by reading each op body. Kept in bijection with snippets.OpNames() by
// the conformance test — adding an op to mcp_bridge.py without a row here fails CI
// (fail-closed). Distribution: 36 readonly, 21 mutating, 4 destructive, 5 exec, 4 scc.
var table = map[string]OpClass{
	"actor_transforms":         {Class: Readonly},                                                              // Iterates get_all_level_actors() and returns loc/rot/scale/class only; pure observation, no editor/wor...
	"apply_level_recipe":       {Class: Exec, SelfTransacted: true, TouchesAsset: true, Gateable: true},        // exec(compile(src,...)) runs an arbitrary Python recipe file plus clean_slate() wipe and save_dirty_pa...
	"asset_deps":               {Class: Readonly},                                                              // AssetRegistry get_dependencies/get_referencers query; reads metadata without loading or writing the a...
	"asset_info":               {Class: Readonly},                                                              // load_asset then reads class/LODs/nanite/bounds; observe-only, never mutates or saves. A read cannot c...
	"asset_query":              {Class: Readonly},                                                              // ARFilter AssetRegistry get_assets/get_blueprint_assets; enumerates without loading, no state change.
	"asset_reimport":           {Class: SCC, TouchesAsset: true, Gateable: true},                               // reimport_assets re-pulls the source file and overwrites on-disk asset content (plan buckets asset_rei...
	"asset_tags":               {Class: Readonly},                                                              // Reads AssetRegistry tag values (ParentClass/NativeParentClass/etc.) without loading the asset; pure o...
	"assign_subclass":          {Class: Mutating, TouchesAsset: true, Gateable: true},                          // set_editor_property on a blueprint CDO then compile_blueprint + save_asset. Reversible property set (...
	"blueprint_add_component":  {Class: Mutating, TouchesAsset: true, Gateable: true},                          // add_new_subobject adds a component to a blueprint, then compile + save_asset. Reversible add persiste...
	"blueprint_create":         {Class: Mutating, TouchesAsset: true, Gateable: true},                          // BlueprintFactory create_asset + save_asset creates a new on-disk blueprint. 'create' is a reversible ...
	"blueprint_set_defaults":   {Class: Mutating, TouchesAsset: true, Gateable: true},                          // Sets CDO default properties, compile_blueprint, save_asset. Reversible property mutation persisted to...
	"capture_list":             {Class: Readonly},                                                              // Enumerates the in-memory _MCP_RECORDERS dict (session/running/frame count); status read, no unreal ca...
	"capture_poll":             {Class: Readonly},                                                              // One-shot status read of a recorder session (frames_captured/elapsed); explicitly not a poll loop and ...
	"capture_poses":            {Class: Readonly, Cancellable: true},                                           // Renders one SceneCapture2D per pose and exports PNGs, spawning+destroying the capture actor net-neutr...
	"capture_start":            {Class: Readonly, Cancellable: true},                                           // Begins a background frame recorder (slate post-tick callback + transient SceneCapture) that renders/o...
	"capture_stop":             {Class: Readonly},                                                              // Tears down the recorder, flushes a manifest, returns collected frame metadata; concludes an observati...
	"cockpit_info":             {Class: Readonly},                                                              // Native-presence probe returning MCPCore transport coords or a not_present sentinel; pure status read ...
	"console":                  {Class: Exec, Gateable: true},                                                  // Runs an arbitrary editor/PIE console command via console_command/execute_console_command (cheats, exe...
	"create_material_instance": {Class: Mutating, TouchesAsset: true, Gateable: true},                          // MaterialInstanceConstantFactory create_asset, sets scalar/vector/texture params, then save_asset. Rev...
	"dataasset_create":         {Class: Mutating, TouchesAsset: true, Gateable: true},                          // DataAssetFactory create_asset + save_asset creates a new on-disk data asset. Reversible create author...
	"datatable_create":         {Class: Mutating, TouchesAsset: true, Gateable: true},                          // DataTableFactory create_asset (with row struct) + save_asset creates a new on-disk datatable. Reversi...
	"datatable_import":         {Class: Mutating, TouchesAsset: true, Gateable: true},                          // fill_data_table_from_json/csv_string populates an existing datatable then save_asset. 'import' is a r...
	"delete_actor":             {Class: Destructive, Gateable: true},                                           // destroy_actor removes a level actor from the world (the canonical destructive op). Removes world stat...
	"design_probe":             {Class: Readonly},                                                              // Iterates level actors to build a class histogram and flag missing meshes/lights/player-starts/nav-bou...
	"editor_ping":              {Class: Readonly},                                                              // Liveness probe: reads _MCP_BRIDGE_VERSION and is_in_play_in_editor flag, returns ok/version/pie/time....
	"editor_state":             {Class: Readonly},                                                              // Observes current level name, PIE flag, viewport camera info, selection labels, actor count, active re...
	"editor_status":            {Class: Readonly},                                                              // Reads engine version, project dir, current level, PIE flag, bridge version, editor PID. Observation o...
	"enum_values":              {Class: Readonly},                                                              // load_object/getattr to resolve a UENUM or UserDefinedEnum and iterate its enumerators. Read-only refl...
	"find_actors":              {Class: Readonly},                                                              // get_all_actors_of_class + get_editor_property reads filtered by a where-map; returns reflected props....
	"focus_actors":             {Class: Mutating},                                                              // Calls set_level_viewport_camera_info, which mutates editor viewport-camera state (not pure readonly)....
	"get_actor":                {Class: Readonly},                                                              // Reads one actor's location/rotation/scale/class/components via getters. Pure observation.
	"get_selection":            {Class: Readonly},                                                              // Returns get_selected_level_actors labels/classes. Read only.
	"import_assets":            {Class: SCC, Cancellable: true, TouchesAsset: true, Gateable: true},            // Batch AssetImportTask with save=True (persists imported assets to disk) and replace_existing=True (ma...
	"instances_count":          {Class: Readonly},                                                              // Iterates ISM/HISM components and sums get_instance_count by mesh. Read only.
	"instances_list":           {Class: Readonly},                                                              // Reads per-instance transforms (bounded by a limit) from ISM/HISM components. Synchronous read that re...
	"level_diff":               {Class: Readonly},                                                              // Compares current actor positions against a stored in-memory snapshot and reports added/removed/moved....
	"level_snapshot":           {Class: Readonly},                                                              // Reads all actor positions/classes into an in-memory Python dict (_MCP_SNAPSHOTS). No editor/world sta...
	"list_actors":              {Class: Readonly},                                                              // Enumerates level actors with an optional name/class filter and returns actor refs. Pure query.
	"list_assets":              {Class: Readonly},                                                              // EditorAssetLibrary.list_assets returns a sorted/truncated list of asset paths. Registry/disk listing;...
	"live_coding_compile":      {Class: Exec, Cancellable: true, Gateable: true},                               // Runs the 'LiveCoding.Compile' console command -> compiles/hot-reloads C++. Explicit exec tier (runs/c...
	"map_gameplay":             {Class: Readonly},                                                              // Discovers WorldSettings GameMode override, project default GameMode, and live mode/state/controller/p...
	"open_level":               {Class: Mutating, TouchesAsset: true, Gateable: true},                          // save_dirty_packages(True,True) then load_level: changes the active world by loading a map asset (targ...
	"pie_destroy":              {Class: Destructive, Gateable: true},                                           // destroy_actor on a live PIE actor. Explicit destructive tier (deletes state); operates on transient g...
	"pie_exec":                 {Class: Exec, Gateable: true},                                                  // actor.call_method(fn, kwargs) invokes an arbitrary named UFunction on a live actor/gamestate -> arbit...
	"pie_input":                {Class: Mutating, Gateable: true},                                              // Injects key input (tap/hold/press/release) into the live game via MCPControlSubsystem -> pie control ...
	"pie_observe":              {Class: Readonly},                                                              // Reflection-driven read of gamestate fields, actor class counts, and actors-of-interest props in the P...
	"pie_screenshot":           {Class: Readonly},                                                              // take_high_res_screenshot captures the rendered PIE frame to Saved/Screenshots (an observation output ...
	"pie_set_property":         {Class: Mutating, Gateable: true},                                              // set_editor_property on a live PIE actor to set test preconditions -> changes actor/game state (transi...
	"reflect_class":            {Class: Readonly},                                                              // Reflects a class's CDO default property values + callables via _reflect_observe; pure read. May load ...
	"reflect_object":           {Class: Readonly},                                                              // Reflects a live object (gamestate/actor) via _reflect_observe; observation only, no editor/asset/worl...
	"save_all":                 {Class: SCC, TouchesAsset: true, Gateable: true},                               // save_dirty_packages(True,True) writes all dirty assets + level to disk — a source-control-relevant pe...
	"scene_apply":              {Class: Mutating, SelfTransacted: true, TouchesAsset: true, Gateable: true},    // compose/apply: spawns+updates mcp_scene-tagged actors inside its own `_transaction` (self-transacted;...
	"scene_bounds":             {Class: Readonly},                                                              // Computes union AABB over selected/globbed level actors; read only.
	"scene_clear":              {Class: Destructive, SelfTransacted: true, TouchesAsset: true, Gateable: true}, // destroy_actor on every actor tagged mcp_scene:<id> inside its own `_transaction`, then save_dirty_pac...
	"scene_restore":            {Class: Mutating, TouchesAsset: true, Gateable: true},                          // Re-applies captured transforms (set_actor_location/rotation/scale3d) then save_dirty_packages. This i...
	"select_actors":            {Class: Mutating},                                                              // set_selected_level_actors changes editor selection (transient UI state), optionally frames the viewpo...
	"set_actor_transform":      {Class: Mutating, Gateable: true},                                              // Sets a level actor's location/rotation/scale via raw calls (no _transaction — cockpit should wrap). D...
	"set_world_gamemode":       {Class: Mutating, TouchesAsset: true, Gateable: true},                          // Sets WorldSettings.default_game_mode then save_dirty_packages (writes level config to disk). No _tran...
	"spawn_actor":              {Class: Mutating, Gateable: true},                                              // spawn_actor_from_class (optionally sets static mesh + label). No save, no _transaction; loads referen...
	"start_play":               {Class: Mutating, Gateable: true},                                              // Enters PIE / simulate (editor_request_begin_play or editor_play_simulate). Editor-state transition th...
	"stop_play":                {Class: Destructive, Gateable: true},                                           // editor_request_end_play ends the PIE session and tears down the game world irreversibly (spec explici...
	"take_screenshot":          {Class: Readonly},                                                              // Renders via a transient SceneCapture2D that is spawned then destroy_actor'd; net world state unchange...
	"viewport_get":             {Class: Readonly},                                                              // Reads viewport camera info + game_view flag; read only.
	"viewport_set":             {Class: Exec, Gateable: true},                                                  // FAIL-CLOSED CATCH: besides setting camera/pilot/game-view, it runs ARBITRARY console commands — `for ...
	"widget_compile":           {Class: SCC, TouchesAsset: true, Gateable: true},                               // compile_blueprint then save_asset writes the WidgetBlueprint to disk. Constrained BP-graph compile (n...
	"widget_compose":           {Class: Mutating, TouchesAsset: true, Gateable: true},                          // Reconciles/adds/patches widget nodes + applies props; optional remove/prune is snapshotted first and ...
	"widget_create":            {Class: Mutating, TouchesAsset: true, Gateable: true},                          // create_asset builds a NEW WidgetBlueprint (parent class + root panel), compile_blueprint, save_asset....
	"widget_describe":          {Class: Readonly},                                                              // Returns the authorable palette/anchor presets, or reflects a widget class via reflect_class; read only.
	"widget_tree":              {Class: Readonly},                                                              // Loads a WBP and returns its canonical tree + digest. mode='restore' is NOT_IMPLEMENTED (returns an er...
	"world_query":              {Class: Readonly},                                                              // Spatial queries (line_trace / sphere_overlap / nav_path / project_point) against the game world; obse...
}
