package tools

import (
	"context"
	"fmt"
	"sort"
	"strings"

	"github.com/jdziat/unreal-mcp-server/internal/session"
	"github.com/jdziat/unreal-mcp-server/internal/tools/spec"
)

//go:generate go run ./gendocs

const generatedNote = "<!-- GENERATED by `go generate ./internal/tools` from the tool spec table — do not edit. -->\n\n"

var toolsetOrder = []spec.Toolset{spec.Core, spec.Daemon, spec.Headless, spec.Design, spec.UI, spec.Desktop, spec.PolyWorld}

var toolsetBlurb = map[spec.Toolset]string{
	spec.Core:      "always on",
	spec.Daemon:    "on in daemon mode (multi-project server)",
	spec.Headless:  "separate UnrealEditor-Cmd processes",
	spec.Design:    "offline design analysis",
	spec.UI:        "UMG authoring",
	spec.Desktop:   "OS-level screen capture and input (Windows)",
	spec.PolyWorld: "the PolyWorld Company-MVP game",
}

// ToolsMarkdown renders docs/tools.md from the specs.
func ToolsMarkdown(specs []*spec.Spec) string {
	var b strings.Builder
	b.WriteString(generatedNote)
	b.WriteString("# Tools\n\n")
	core := 0
	for _, s := range specs {
		if s.Toolset == spec.Core {
			core++
		}
	}
	fmt.Fprintf(&b, "%d tools (%d core). Optional toolsets are enabled per session with `toolsets op=enable` or a project's "+
		"`.umcp.json` `toolsets`. Every tool takes JSON arguments validated against its schema; errors come back as "+
		"`{\"error\": {code, message, hint, retryable, outcome, details}}` with a closed code set.\n\n", len(specs), core)
	b.WriteString("**Tiers** (per op; a tool's annotations follow its worst op): `readonly` · `ephemeral` (UI/session state, " +
		"server-owned scratch files) · `mutating` (project/world content; nothing authored is lost) · `destructive` (can lose " +
		"authored content; approval-gated when the gate policy requires) · `exec` (runs caller-supplied code/input; gated).\n\n" +
		"**Needs**: every tool needs a live editor unless marked offline; ops may also need `pie` (a running play session), " +
		"`plugin` (the UnrealMCP C++ plugin), `navmesh`, `project` (a configured project directory) or `engine`.\n\n" +
		"**Rollback ladder**: `snapshot_restore` (transforms) → `scene_clear` (a scene's actors) → `git_revert` (files, to a " +
		"`git op=checkpoint`).\n\n")
	bySet := map[spec.Toolset][]*spec.Spec{}
	for _, s := range specs {
		bySet[s.Toolset] = append(bySet[s.Toolset], s)
	}
	b.WriteString("| Toolset | Tools |\n|---|---|\n")
	for _, ts := range toolsetOrder {
		var names []string
		for _, s := range bySet[ts] {
			names = append(names, "`"+s.Name+"`")
		}
		fmt.Fprintf(&b, "| %s (%s) | %s |\n", ts, toolsetBlurb[ts], strings.Join(names, ", "))
	}
	for _, ts := range toolsetOrder {
		if len(bySet[ts]) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\n## Toolset `%s`\n", ts)
		for _, s := range bySet[ts] {
			writeTool(&b, s)
		}
	}
	return b.String()
}

func writeTool(b *strings.Builder, s *spec.Spec) {
	flags := []string{"tier " + s.Tier().String()}
	if s.Offline {
		flags = append(flags, "offline")
	}
	fmt.Fprintf(b, "\n### `%s` — %s\n\n_%s_\n\n%s\n\n", s.Name, s.Title, strings.Join(flags, " · "), s.Description)
	if len(s.Ops) > 1 || s.Ops[0].Name != "" {
		b.WriteString("| op | tier | does | required | needs |\n|---|---|---|---|---|\n")
	} else {
		b.WriteString("| tier | required | needs |\n|---|---|---|\n")
	}
	for _, op := range s.Ops {
		req := strings.Join(op.Required, ", ")
		if len(s.Ops) == 1 && s.Ops[0].Name == "" && s.Schema != nil {
			req = strings.Join(s.Schema.Required, ", ")
		}
		needs := append([]string{}, op.Needs...)
		if !s.Offline {
			needs = append([]string{"editor"}, needs...)
		}
		tier := op.Tier.String()
		if op.Async || s.Async {
			tier += ", async"
		}
		if len(s.Ops) == 1 && op.Name == "" {
			fmt.Fprintf(b, "| %s | %s | %s |\n", tier, req, strings.Join(needs, ", "))
			continue
		}
		fmt.Fprintf(b, "| `%s` | %s | %s | %s | %s |\n", op.Name, tier, op.Summary, req, strings.Join(needs, ", "))
	}
	if s.Schema == nil || len(s.Schema.Properties) == 0 {
		return
	}
	b.WriteString("\n| param | type | description |\n|---|---|---|\n")
	var keys []string
	for k := range s.Schema.Properties {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		p := s.Schema.Properties[k]
		typ := p.Type
		if typ == "" && len(p.Types) > 0 {
			typ = strings.Join(p.Types, "|")
		}
		if typ == "array" && p.Items != nil {
			typ = p.Items.Type + "[]"
		}
		desc := p.Description
		if len(p.Enum) > 0 {
			var vals []string
			for _, v := range p.Enum {
				vals = append(vals, fmt.Sprint(v))
			}
			if desc == "" {
				desc = "one of: " + strings.Join(vals, ", ")
			} else {
				desc += " — one of: " + strings.Join(vals, ", ")
			}
		}
		fmt.Fprintf(b, "| `%s` | %s | %s |\n", k, typ, strings.ReplaceAll(desc, "|", "\\|"))
	}
}

// MigrationMarkdown renders docs/migration-v2.md: every v1 tool name and its v2 call.
func MigrationMarkdown(specs []*spec.Spec) string {
	var b strings.Builder
	b.WriteString(generatedNote)
	b.WriteString("# Migrating from v1 to v2\n\n")
	v1 := V1Tools()
	fmt.Fprintf(&b, "v2 replaces v1's %d tools with %d. Tool names are not compatible: update prompts, scripts and "+
		"`.mcp.json` allow-lists using the table below. The v1 server is recoverable from tag `v1-final`.\n\n", len(v1), len(specs))
	b.WriteString("## What changed everywhere\n\n" +
		"- **One op per call.** Multi-operation tools take `op` (e.g. `actor_query op=list`). Per-op required parameters are " +
		"checked before the editor is touched (`INVALID_ARGUMENT` lists what is missing or not accepted).\n" +
		"- **Worlds.** `world` is `editor` | `pie` | `auto` (v1's `game` is `pie`). Edits (`actor_edit`) require it explicitly; " +
		"`auto` is accepted only by read-only tools; an unknown world is an error, never a silent fallback.\n" +
		"- **Actor references.** `actor` is a label, an object path, or (PIE) `@gamestate`, `@pawn`, `@controller`. A label " +
		"shared by several actors is `CONFLICT` with the candidate paths — v1 silently used the first match.\n" +
		"- **Classes.** `class` accepts `/Script/Module.Class`, a `/Game` Blueprint, `Module.Class` or a short name; ambiguous " +
		"short names are `CONFLICT`.\n" +
		"- **Vectors.** `location` / `rotation` ([pitch, yaw, roll]) / `scale` are `[x, y, z]` arrays (v1 `x`/`y`/`z` scalars " +
		"and `camera_location`/`camera_rotation_pyr` are gone).\n" +
		"- **Results** are always objects (`structuredContent`), never bare arrays; images arrive as image content.\n" +
		"- **Errors** are one envelope with a closed code set; `outcome:\"unknown\"` marks a mutating call that may have " +
		"run (do not blindly retry).\n" +
		"- **Long work is async**: `build`, `playtest op=run`, `editor_lifecycle`, `git_revert`, `headless` return a job; pass " +
		"`wait_s` (≤ 25) or poll `job`.\n" +
		"- **Safety**: overwrites and deletions are separate destructive ops (`asset_create op=replace`, `scene_clear op=prune`, " +
		"`widget_edit op=prune`); `python op=recipe` no longer wipes the level by default; output files are server-owned.\n\n")
	b.WriteString("## Tool by tool\n\nTools outside the core toolset are marked: enable them first with `toolsets op=enable " +
		"toolset=<name>` (or a project's `.umcp.json` `toolsets`, or `-toolsets`). The daemon's `project` tool is on in " +
		"daemon mode.\n\n| v1 tool | v2 call |\n|---|---|\n")
	replacedBy := map[string]string{}
	toolsetOf := map[string]spec.Toolset{}
	for _, s := range specs {
		toolsetOf[s.Name] = s.Toolset
		for _, r := range s.Replaces {
			replacedBy[r] = s.Name
		}
	}
	for _, name := range v1 {
		switch {
		case DroppedV1[name]:
			fmt.Fprintf(&b, "| `%s` | — removed (its editor op never existed) |\n", name)
		case V1Calls[name] != "":
			call := V1Calls[name]
			if tool, rest, ok := strings.Cut(call, " "); ok {
				call = "`" + tool + "` " + rest
			} else {
				call = "`" + call + "`"
			}
			if ts := toolsetOf[replacedBy[name]]; ts != spec.Core {
				call += fmt.Sprintf(" — toolset `%s`", ts)
			}
			fmt.Fprintf(&b, "| `%s` | %s |\n", name, call)
		default:
			fmt.Fprintf(&b, "| `%s` | `%s` |\n", name, replacedBy[name])
		}
	}
	return b.String()
}

// docsProjects stands in for the daemon so CatalogForDocs includes the project tool.
type docsProjects struct{}

func (docsProjects) Attach(context.Context, string, string) (string, error) { return "", nil }
func (docsProjects) Release(string)                                         {}
func (docsProjects) List(string) []session.ProjectInstance                  { return nil }

// CatalogForDocs is every tool, daemon-only ones included.
func CatalogForDocs() []*spec.Spec { return Specs(Deps{Projects: docsProjects{}}) }
