package tools

import (
	_ "embed"
	"strings"
)

// The v1 → v2 migration record (docs/plans/OVERHAUL_PLAN.md §2.3). The bijection over
// the 155 v1 names is enforced by TestMigrationAccounting; docs/migration-v2.md is
// generated from it.

//go:embed testdata/v1_tools.txt
var v1ToolsTxt string

// V1Tools is every tool name v1 advertised (captured from a live tools/list of both
// stdio — with the cockpit wired — and daemon mode).
func V1Tools() []string { return strings.Fields(v1ToolsTxt) }

// DroppedV1 are v1 tools retired without a v2 replacement (plan §2.3 row 46): they
// were advertised, but their companion ops never existed (UNKNOWN_OP).
var DroppedV1 = map[string]bool{
	"widget_view": true, "widget_set_fields": true, "widget_inspect": true, "widget_read": true,
	"widget_capture": true, "widget_bind_field": true, "widget_track_actor": true, "set_input_mode": true,
	"widget_set_focus": true, "pie_set_source": true, "set_hud_widget": true, "widget_bind_event": true,
	"ui_click": true, "widget_viewmodel_create": true, "widget_bind_mvvm": true, "widget_make_rt_material": true,
}

// V1Calls is the exact v2 call for each replaced v1 tool (the tool comes first; it
// must match the tool whose Replaces lists the v1 name).
var V1Calls = map[string]string{
	"affordances":              "toolsets op=describe",
	"apply_level_recipe":       "python op=recipe (clean_slate now defaults false)",
	"asset_deps":               "asset_query op=deps",
	"asset_info":               "asset_query op=info",
	"asset_query":              "asset_query op=search (class_paths → classes, package_paths → folder)",
	"asset_reimport":           "asset_import op=reimport",
	"asset_tags":               "asset_query op=tags",
	"asset_thumbnail":          "asset_query op=thumbnail (returns the PNG)",
	"asset_utilization":        "design_audit kind=utilization",
	"assign_subclass":          "asset_edit op=assign_subclass (target → asset, prop → property, class_path → class)",
	"audio_audit":              "design_audit kind=audio",
	"audio_capture_start":      "audio op=capture_start (PIE only)",
	"audio_capture_stop":       "audio op=capture_stop (writes Saved/MCP/audio)",
	"balance_sweep":            "design_explore op=sweep",
	"blueprint_add_component":  "asset_edit op=add_component (blueprint → asset, component_class → class)",
	"blueprint_create":         "asset_create op=create kind=blueprint (parent_class_path → class)",
	"blueprint_set_defaults":   "asset_edit op=set_defaults (blueprint → asset, defaults → properties)",
	"build_compile":            "build (strategy full → ubt)",
	"capture_clear":            "capture op=clear (session, or all=true)",
	"capture_start":            "capture op=start (camera_location/rotation_pyr → location/rotation)",
	"capture_status":           "capture op=status",
	"capture_stop":             "capture op=stop",
	"cockpit_url":              "toolsets op=describe (cockpit.url, without the access token)",
	"company_build":            "polyworld op=build (PIE only)",
	"company_demolish":         "polyworld_demolish (PIE only)",
	"company_road":             "polyworld op=road (PIE only)",
	"company_select":           "polyworld op=select (PIE only)",
	"company_status":           "polyworld op=status (PIE only)",
	"create_material_instance": "asset_create op=create kind=material_instance",
	"dataasset_create":         "asset_create op=create kind=data_asset",
	"datatable_create":         "asset_create op=create kind=data_table",
	"datatable_import":         "asset_import op=datatable (datatable → asset)",
	"decision_audit":           "design_audit kind=decision",
	"delete_actor":             "actor_edit op=delete world=editor (actor_label → actor)",
	"design_check":             "scene op=check",
	"design_explore":           "design_explore op=explore",
	"editor_events":            "logs op=events (since_offset → marker)",
	"editor_ping":              "editor op=ping",
	"editor_restart":           "editor_lifecycle op=restart (safe shutdown; save / discard_dirty)",
	"editor_state":             "editor op=status",
	"editor_status":            "editor op=status",
	"enum_values":              "reflect op=enum (enum_path → enum)",
	"env_preset_apply":         "scene op=env_preset",
	"execute_console_command":  "console (world editor|pie)",
	"execute_python":           "python op=run",
	"feel_audit":               "design_audit kind=feel",
	"find_actors":              "actor_query op=find (class_path → class, reflect → properties)",
	"focus_actors":             "viewport op=focus (targets → actors)",
	"focus_window":             "desktop_input op=focus",
	"gameplay_tag_add":         "project_config op=gameplay_tag",
	"get_actor":                "actor_query op=get (actor_label → actor)",
	"get_selection":            "viewport op=selection",
	"git_checkpoint":           "git op=checkpoint (also tags umcp/cp/<n>)",
	"git_diff":                 "git op=diff",
	"git_log":                  "git op=log",
	"git_revert_to":            "git_revert to=<checkpoint> (checkpoints only; editor-aware)",
	"git_status":               "git op=status",
	"headless_run":             "headless op=commandlet|exec|tests (async)",
	"health_check":             "editor op=health",
	"image_compare":            "analyze op=image_diff (a → path, b → baseline)",
	"import_assets":            "asset_import op=files (file_paths → files, destination_path → folder)",
	"in_motion_audit":          "design_audit kind=in_motion",
	"input_action":             "project_config op=input_action",
	"input_axis":               "project_config op=input_axis",
	"instances_count":          "world_query op=instances_count",
	"instances_list":           "world_query op=instances_list",
	"job_cancel":               "job op=cancel",
	"job_status":               "job op=status (or op=wait)",
	"key_press":                "desktop_input op=keys (keys/sequence → keys list)",
	"layout_preview":           "scene op=preview",
	"level_diff":               "snapshot op=diff",
	"level_snapshot":           "snapshot op=take",
	"list_actors":              "actor_query op=list",
	"list_assets":              "asset_query op=list (path → folder)",
	"list_windows":             "desktop_capture op=list_windows",
	"live_coding_compile":      "build strategy=livecoding",
	"logs_mark":                "logs op=mark",
	"logs_since":               "logs op=since",
	"logs_tail":                "logs op=tail",
	"luminance_report":         "design_audit kind=luminance",
	"map_gameplay":             "project_map op=level",
	"mouse_control":            "desktop_input op=mouse",
	"novelty_audit":            "design_audit kind=novelty",
	"open_level":               "level op=open (level_path → level)",
	"pawn_state":               "pie_observe pawn=true",
	"perf_parse":               "analyze op=perf (file → path)",
	"pie_destroy":              "actor_edit op=delete world=pie",
	"pie_exec":                 "actor_call (target → actor, ufunction → function; gamestate → @gamestate)",
	"pie_input":                "pie op=input",
	"pie_observe":              "pie_observe (actors_of_interest → actors)",
	"pie_screenshot":           "screenshot op=pie",
	"pie_set_property":         "actor_edit op=set_properties world=pie",
	"pie_verify":               "actor_call until=<predicate>",
	"pie_wait_until":           "pie_wait",
	"play_test_sound":          "audio op=play",
	"playtest_capture":         "playtest op=run (a scenario/v1; async)",
	"playtest_evaluate":        "analyze op=rubric",
	"primitive_audit":          "design_audit kind=primitive",
	"project_attach":           "project op=attach",
	"project_ensure_open":      "editor_lifecycle op=ensure_open",
	"project_list":             "project op=list",
	"project_map":              "project_map op=project",
	"project_release":          "project op=release",
	"read_capture":             "capture op=read (dir → path)",
	"reflect_class":            "reflect op=class (class_path → class)",
	"reflect_object":           "reflect op=object (target → actor; gamestate → @gamestate, pawn → @pawn, playercontroller → @controller)",
	"render_health":            "design_audit kind=render",
	"save_all":                 "level op=save_all",
	"scenario_list":            "analyze op=scenarios",
	"scenario_run":             "playtest op=run (async)",
	"scene_apply":              "scene op=apply (spec_path → path, spec_json → json; prune → scene_clear op=prune)",
	"scene_clear":              "scene_clear op=all",
	"scene_contact_sheet":      "screenshot op=orbit (target → actors)",
	"scene_digest":             "snapshot op=digest",
	"scene_plan":               "scene op=apply dry_run=true",
	"scene_restore":            "snapshot_restore (by object path)",
	"scene_snapshot":           "snapshot op=take",
	"screen_capture":           "desktop_capture op=screen",
	"select_actors":            "viewport op=select (labels → actors)",
	"set_actor_transform":      "actor_edit op=transform world=editor (location/rotation/scale as [x,y,z])",
	"set_gamemode":             "project_config op=set_default_gamemode (class_path → class)",
	"set_world_gamemode":       "level op=set_world_gamemode (class_path → class)",
	"spawn_actor":              "actor_edit op=spawn world=editor (class_path → class, x/y/z → location)",
	"start_play":               "pie op=start (waits until running)",
	"stop_play":                "pie op=stop",
	"style_cohesion":           "design_audit kind=style",
	"take_screenshot":          "screenshot op=viewport (camera_location/rotation_pyr → location/rotation)",
	"type_text":                "desktop_input op=type",
	"verb_response":            "design_audit kind=verb",
	"viewport_get":             "viewport op=get",
	"viewport_set":             "viewport op=set (console → the console tool)",
	"widget_compile":           "widget_edit op=compile (blueprint → asset)",
	"widget_compose":           "widget_edit op=compose | op=prune (prune/remove need op=prune)",
	"widget_create":            "asset_create op=create kind=widget_blueprint",
	"widget_describe":          "widget_query op=describe (widget_class → class)",
	"widget_render":            "widget_query op=render (widget_class → class; out_path is server-owned)",
	"widget_tree":              "widget_query op=tree (blueprint → asset; mode=restore was never implemented)",
	"window_capture":           "desktop_capture op=window (focus → desktop_input op=focus first)",
	"world_query":              "world_query op=line_trace|sphere_overlap|nav_path|project_point (kind → op)",
}
